trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  subscriptionId: 'd8cd2f9e-2816-4fe8-b17e-82f9204cab2e'
  azureResourceManagerConnection: 'prod100'
  storageAccountName: 'prod100'
  storageAccountConnectionString: $STORAGECONNECTIONSTRING
  containerName: templates$(Build.BuildId)

stages:
- stage: 'PublishTemplates'
  displayName: 'Publish Templates'
  jobs: 
    - job: 'PublishTemplates'
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo $STORAGECONNECTIONSTRING
            echo $(build.artifactstagingdirectory)
            echo $(Build.BuildId)
            echo Hello world
      - task: CopyFiles@2
        displayName: 'Copy composing to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: 'Chapter 05'
          Contents:  
            '**/*'
            
          TargetFolder: '$(build.artifactstagingdirectory)/templates'
      - task: AzureCLI@2
        displayName: "Create container $(Build.BuildId)"
        inputs:
          azureSubscription: ${{ variables.azureResourceManagerConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage container create --connection-string "${{ variables.storageAccountConnectionString }}" -n ${{ variables.containerName }} --account-name ${{ variables.storageAccountName }}'
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ variables.azureResourceManagerConnection }}
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob upload-batch --account-name ${{ variables.storageAccountName }} -d ${{ variables.containerName }} -s TargetFolder --connection-string "${{ variables.storageAccountConnectionString }}"'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
- stage: 'DelployTemplates'
  displayName: 'Deploy Templates'
  jobs: 
    - job: 'DelployTemplates'
      steps:

      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
          
          
      - task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
        inputs:
          sourcePath: '$(System.DefaultWorkingDirectory)/drop/templates/Composing/'
          filePattern: 'Main.parameters.test.json'
          tokenRegex:  '(ad\w+)bc'
